version: '3.7'

services:

  db:
    build: './database'
    restart: always
    environment:
        - "POSTGRES_DB_USER=ivsa"
        - "POSTGRES_DB_PASSWORD=ivsa01"
        - "POSTGRES_DB_DATABASE=db_emp"
        - "POSTGRES_PASSWORD=password"
    ports:
        - 5432:5432

#  app:
#    build: .
#    ports:
#      - "8080:8080"
##    depends_on:
##      - db