version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 25368

  app:
    image: request
    ports:
      - "8080:8080"
#    depends_on:
#      - db